/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inDevelopment' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UrgencyLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const ReportRequest = IDL.Record({
  'businessObjective' : IDL.Text,
  'status' : Status,
  'justification' : IDL.Text,
  'reviewerComments' : IDL.Opt(IDL.Text),
  'urgencyLevel' : UrgencyLevel,
  'dataSource' : IDL.Text,
  'assignedReviewer' : IDL.Opt(IDL.Principal),
  'requiredKPIs' : IDL.Text,
  'submissionDate' : Time,
  'requesterName' : IDL.Text,
  'department' : IDL.Text,
  'requiredFilters' : IDL.Text,
});
export const ReviewInput = IDL.Record({
  'status' : Status,
  'reviewerComments' : IDL.Opt(IDL.Text),
  'assignedReviewer' : IDL.Opt(IDL.Principal),
});
export const ReportRequestInput = IDL.Record({
  'businessObjective' : IDL.Text,
  'justification' : IDL.Text,
  'urgencyLevel' : UrgencyLevel,
  'dataSource' : IDL.Text,
  'requiredKPIs' : IDL.Text,
  'requesterName' : IDL.Text,
  'department' : IDL.Text,
  'requiredFilters' : IDL.Text,
});

export const idlService = IDL.Service({
  'getRequests' : IDL.Func([], [IDL.Vec(ReportRequest)], ['query']),
  'reviewRequest' : IDL.Func([IDL.Principal, ReviewInput], [], []),
  'submitRequest' : IDL.Func([ReportRequestInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inDevelopment' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UrgencyLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReportRequest = IDL.Record({
    'businessObjective' : IDL.Text,
    'status' : Status,
    'justification' : IDL.Text,
    'reviewerComments' : IDL.Opt(IDL.Text),
    'urgencyLevel' : UrgencyLevel,
    'dataSource' : IDL.Text,
    'assignedReviewer' : IDL.Opt(IDL.Principal),
    'requiredKPIs' : IDL.Text,
    'submissionDate' : Time,
    'requesterName' : IDL.Text,
    'department' : IDL.Text,
    'requiredFilters' : IDL.Text,
  });
  const ReviewInput = IDL.Record({
    'status' : Status,
    'reviewerComments' : IDL.Opt(IDL.Text),
    'assignedReviewer' : IDL.Opt(IDL.Principal),
  });
  const ReportRequestInput = IDL.Record({
    'businessObjective' : IDL.Text,
    'justification' : IDL.Text,
    'urgencyLevel' : UrgencyLevel,
    'dataSource' : IDL.Text,
    'requiredKPIs' : IDL.Text,
    'requesterName' : IDL.Text,
    'department' : IDL.Text,
    'requiredFilters' : IDL.Text,
  });
  
  return IDL.Service({
    'getRequests' : IDL.Func([], [IDL.Vec(ReportRequest)], ['query']),
    'reviewRequest' : IDL.Func([IDL.Principal, ReviewInput], [], []),
    'submitRequest' : IDL.Func([ReportRequestInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };