/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ReportRequest {
  'businessObjective' : string,
  'status' : Status,
  'justification' : string,
  'reviewerComments' : [] | [string],
  'urgencyLevel' : UrgencyLevel,
  'dataSource' : string,
  'assignedReviewer' : [] | [Principal],
  'requiredKPIs' : string,
  'submissionDate' : Time,
  'requesterName' : string,
  'department' : string,
  'requiredFilters' : string,
}
export interface ReportRequestInput {
  'businessObjective' : string,
  'justification' : string,
  'urgencyLevel' : UrgencyLevel,
  'dataSource' : string,
  'requiredKPIs' : string,
  'requesterName' : string,
  'department' : string,
  'requiredFilters' : string,
}
export interface ReviewInput {
  'status' : Status,
  'reviewerComments' : [] | [string],
  'assignedReviewer' : [] | [Principal],
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'inDevelopment' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export type UrgencyLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface _SERVICE {
  'getRequests' : ActorMethod<[], Array<ReportRequest>>,
  'reviewRequest' : ActorMethod<[Principal, ReviewInput], undefined>,
  'submitRequest' : ActorMethod<[ReportRequestInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];