/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReportRequestInput {
    businessObjective: string;
    justification: string;
    urgencyLevel: UrgencyLevel;
    dataSource: string;
    requiredKPIs: string;
    requesterName: string;
    department: string;
    requiredFilters: string;
}
export type Time = bigint;
export interface ReviewInput {
    status: Status;
    reviewerComments?: string;
    assignedReviewer?: Principal;
}
export interface ReportRequest {
    businessObjective: string;
    status: Status;
    justification: string;
    reviewerComments?: string;
    urgencyLevel: UrgencyLevel;
    dataSource: string;
    assignedReviewer?: Principal;
    requiredKPIs: string;
    submissionDate: Time;
    requesterName: string;
    department: string;
    requiredFilters: string;
}
export enum Status {
    pending = "pending",
    completed = "completed",
    inDevelopment = "inDevelopment",
    approved = "approved",
    rejected = "rejected"
}
export enum UrgencyLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    getRequests(): Promise<Array<ReportRequest>>;
    reviewRequest(user: Principal, input: ReviewInput): Promise<void>;
    submitRequest(input: ReportRequestInput): Promise<void>;
}
import type { ReportRequest as _ReportRequest, ReportRequestInput as _ReportRequestInput, ReviewInput as _ReviewInput, Status as _Status, Time as _Time, UrgencyLevel as _UrgencyLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getRequests(): Promise<Array<ReportRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async reviewRequest(arg0: Principal, arg1: ReviewInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewRequest(arg0, to_candid_ReviewInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewRequest(arg0, to_candid_ReviewInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitRequest(arg0: ReportRequestInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRequest(to_candid_ReportRequestInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRequest(to_candid_ReportRequestInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ReportRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportRequest): ReportRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UrgencyLevel_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UrgencyLevel): UrgencyLevel {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessObjective: string;
    status: _Status;
    justification: string;
    reviewerComments: [] | [string];
    urgencyLevel: _UrgencyLevel;
    dataSource: string;
    assignedReviewer: [] | [Principal];
    requiredKPIs: string;
    submissionDate: _Time;
    requesterName: string;
    department: string;
    requiredFilters: string;
}): {
    businessObjective: string;
    status: Status;
    justification: string;
    reviewerComments?: string;
    urgencyLevel: UrgencyLevel;
    dataSource: string;
    assignedReviewer?: Principal;
    requiredKPIs: string;
    submissionDate: Time;
    requesterName: string;
    department: string;
    requiredFilters: string;
} {
    return {
        businessObjective: value.businessObjective,
        status: from_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        justification: value.justification,
        reviewerComments: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.reviewerComments)),
        urgencyLevel: from_candid_UrgencyLevel_n7(_uploadFile, _downloadFile, value.urgencyLevel),
        dataSource: value.dataSource,
        assignedReviewer: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.assignedReviewer)),
        requiredKPIs: value.requiredKPIs,
        submissionDate: value.submissionDate,
        requesterName: value.requesterName,
        department: value.department,
        requiredFilters: value.requiredFilters
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inDevelopment: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "inDevelopment" in value ? Status.inDevelopment : "approved" in value ? Status.approved : "rejected" in value ? Status.rejected : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): UrgencyLevel {
    return "low" in value ? UrgencyLevel.low : "high" in value ? UrgencyLevel.high : "medium" in value ? UrgencyLevel.medium : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportRequest>): Array<ReportRequest> {
    return value.map((x)=>from_candid_ReportRequest_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ReportRequestInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportRequestInput): _ReportRequestInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewInput): _ReviewInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UrgencyLevel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): _UrgencyLevel {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    reviewerComments?: string;
    assignedReviewer?: Principal;
}): {
    status: _Status;
    reviewerComments: [] | [string];
    assignedReviewer: [] | [Principal];
} {
    return {
        status: to_candid_Status_n12(_uploadFile, _downloadFile, value.status),
        reviewerComments: value.reviewerComments ? candid_some(value.reviewerComments) : candid_none(),
        assignedReviewer: value.assignedReviewer ? candid_some(value.assignedReviewer) : candid_none()
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessObjective: string;
    justification: string;
    urgencyLevel: UrgencyLevel;
    dataSource: string;
    requiredKPIs: string;
    requesterName: string;
    department: string;
    requiredFilters: string;
}): {
    businessObjective: string;
    justification: string;
    urgencyLevel: _UrgencyLevel;
    dataSource: string;
    requiredKPIs: string;
    requesterName: string;
    department: string;
    requiredFilters: string;
} {
    return {
        businessObjective: value.businessObjective,
        justification: value.justification,
        urgencyLevel: to_candid_UrgencyLevel_n16(_uploadFile, _downloadFile, value.urgencyLevel),
        dataSource: value.dataSource,
        requiredKPIs: value.requiredKPIs,
        requesterName: value.requesterName,
        department: value.department,
        requiredFilters: value.requiredFilters
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    inDevelopment: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.inDevelopment ? {
        inDevelopment: null
    } : value == Status.approved ? {
        approved: null
    } : value == Status.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == UrgencyLevel.low ? {
        low: null
    } : value == UrgencyLevel.high ? {
        high: null
    } : value == UrgencyLevel.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
